### ISSUE TITLE
Replace GUID generator

### ISSUE THREAD

**Issue by peterekepeter** [bunnytrack/umx-converter#2]
Generating GUIDs using `Math.random()` is of questionable quality at best, and has chances of creating a package with conflicting GUID

More info here:

https://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid

**Comment by sapphire-bt** [comment]
Thanks for the link. I'm pretty sure I saw this as I was making the plugin, but for some reason I assumed Crypto was a third-party module (which I wanted to avoid), hence why I opted for the native `Math.random()`.

Expect an update soon!

**Comment by peterekepeter** [comment]
yep, good job on https://github.com/bunnytrack/umx-converter/commit/f3593a1f895b65001b964e6b99786f1c14b17f9d
