### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by Emendo12** [bunnytrack/umx-converter#4]
I kind of need my converted audio to be a quarter MB. Is it possible to tweak this software to compress the output file further? 
The lowest I can get with it right now is 2MB.

**Comment by sapphire-bt** [comment]
Assuming your 2 MB file is the result of using the lowest settings (8-bit/11 kHz/mono) then I don't think there's any way you'll get it down to ~250 kB.

Not sure if this would be suitable for your use case but I believe Vorbis audio can now be used thanks to the recent [UT patches](https://github.com/OldUnreal/UnrealTournamentPatches) by OldUnreal. As Vorbis uses lossy compression (unlike this plugin which ultimately converts everything to Waveform Audio) you should be able to achieve a decent level of compression.
