### ISSUE TITLE
File names with a hyphen are renamed without hyphen resulting in existing UMX replacement failing

### ISSUE THREAD

**Issue by SpectrumTwist** [bunnytrack/umx-converter#5]
If a filename for example "Razor-ub" which is a official UMX file in the unreal tournament music folder, is submitted as an MP3, the resulting saved UMX converted file will be renamed to "Razorub" which the underlying UMX "it" nomenclature in the file seen by the unreal engine will also be Razorub, resulting in that file not being played if the original Razor-ub file is replaced with the new one, EVEN if the UMX is renamed to replace it, the UMX internal file name will remain Razorub and the game simply will simply report that it cannot find the UMX to be played.

**Comment by sapphire-bt** [comment]
Hi there.

In theory, it should just be as simple as changing this line: https://github.com/bunnytrack/umx-converter/blob/main/js/umx-converter.js#L700

I haven't tested it though as I've not had time to sit down and properly test/look into this, but hopefully I will soon; will keep you updated.

Thanks.

**Comment by sapphire-bt** [comment]
Fixed in 3a3ba84be6124f5d3fd1bfe2ed6b4b00ad1f695a.
